/*
 * Automatically generated by 'ng g ng-alain:plugin icon'
 */

import { FullscreenExitOutline, FullscreenOutline, GlobalOutline, LockOutline, LogoutOutline, UserOutline } from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [FullscreenExitOutline, FullscreenOutline, GlobalOutline, LockOutline, LogoutOutline, UserOutline];
